import asyncio
import hashlib
import json
import logging
from typing import List, Dict
from keeper.direct_api import anchor_contribution, poll_execution

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("Phase5-Anchor")

async def run_phase5_anchor(findings: List[Dict]) -> List[Dict]:
    """
    Iterate through the agent's findings and ensure onchain anchoring 
    for those that are CONFIRMED or LIKELY but do not have a tx_hash.
    """
    logger.info(f"🛡️ [Phase 5] Checking anchoring for {len(findings)} findings...")
    
    anchored_results = []

    for finding in findings:
        # We only anchor confirmed findings (CONFIRMED or LIKELY)
        if finding.get("confidence") not in ["CONFIRMED", "LIKELY"]:
            continue

        # If already anchored during Phase 4, we skip
        if finding.get("tx_hash"):
            logger.info(f"Already anchored : {finding['title']}")
            anchored_results.append(finding)
            continue

        # Generate pattern_hash (SHA-256 of title + reason for uniqueness)
        content_to_hash = f"{finding['title']}-{finding['reason']}"
        pattern_hash = hashlib.sha256(content_to_hash.encode()).hexdigest()
        
        # The root_hash_0g is normally transmitted in the scope or generated by the OG storage
        # For the demo, we use a fictitious hash if absent
        root_hash_0g = finding.get("root_hash", "0x" + "a" * 64)

        logger.info(f"Anchoring : {finding['title']}...")
        
        try:
            # 1. Direct Execution API call
            # On utilise l'adresse de réception du serveur comme placeholder car récompense = 0.0
            placeholder_addr = os.getenv("RECEIVER_ADDRESS", "0x" + "0" * 40)
            exec_id = await anchor_contribution(pattern_hash, root_hash_0g, placeholder_addr, amount_usdc=0.0)
            
            if exec_id:
                # 2. Polling to get the final transactionHash
                logger.info(f"  → Execution ID: {exec_id}. Waiting for confirmation...")
                tx_hash = await poll_execution(exec_id)
                
                if tx_hash:
                    finding["tx_hash"] = tx_hash
                    finding["pattern_hash"] = pattern_hash
                    logger.info(f"  Success ! Tx: {tx_hash}")
                else:
                    logger.warning(f"  Timeout or polling failure for {exec_id}")
            else:
                logger.error(f"  Failure of the initial call for {finding['title']}")
        
        except Exception as e:
            logger.error(f"   Critical error during anchoring : {e}")

        anchored_results.append(finding)

    return anchored_results